echo Formating server.cpp
clang-format -style=file -i ./server.cpp
echo Building server-linux-x64...
g++ ./server.cpp -lpthread -O2 -o ./server-linux-x64 -s -m64
echo Building server-linux-x86...
g++ ./server.cpp -lpthread -O2 -o ./server-linux-x86 -s -m32
echo Building server-win64...
x86_64-w64-mingw32-g++-posix ./server.cpp -lws2_32 -O2 -o ./server-win64.exe -s -m64 -static
echo Building server-win32...
i686-w64-mingw32-g++-posix ./server.cpp -lws2_32 -O2 -o ./server-win32.exe -s -m32 -static
